version: 2.1

orbs:
  node: circleci/node@7.1.1

executors:
  build-docker-image:
    docker:
      - image: cimg/base:2025.06
    resource_class: small

  cypress-build-internal:
    docker:
      - image: cypress/build-internal
    environment:
      PLATFORM: linux
    resource_class: small

  linux-x64:
    docker:
      - image: node:22.15.1-bullseye-slim
    environment:
      PLATFORM: linux
    resource_class: small

commands:
  prepare-environment:
    steps:
      - checkout:
          path: .
          depth: 1
      - node/install-packages:
          pkg-manager: yarn
          with-cache: true
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: cypress

  use-prepared-env:
    steps:
      - attach_workspace:
          at: .

jobs:
  build-image:
    executor: build-docker-image
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Create Build Environment
          command: docker build -t cypress/build-internal -f .circleci/Dockerfile .
  build:
    executor: cypress-build-internal
    steps:
      - prepare-environment
  lint:
    executor: linux-x64
    steps:
      - use-prepared-env
      - run:
          name: Lint
          command: |
            lerna run lint

workflows:
  pull-request:
    jobs:
      - build-image
      - build:
          requires:
            - build-image
      - lint:
          requires:
            - build
