executors:
    bullseye:
        docker:
            - image: node:22.15.1-bullseye-slim
        environment:
            PLATFORM: linux
        resource_class: small
jobs:
    lint:
        executor: bullseye
        steps:
            - checkout:
                depth: 1
                path: .
            - node/install-packages:
                pkg-manager: yarn
                with-cache: true
            - run: yarn build
orbs:
    node: circleci/node@7.1.1
setup: true
version: 2.1
workflows:
    pull-request:
        jobs:
            - lint

