steps:
  - when:
      condition:
        or:
          - equal: [ << pipeline.parameters.persist_artifacts >>, true ]
          - equal: [ develop, << pipeline.git.branch >> ]
          - equal: [ 'update-v8-snapshot-cache-on-develop', << pipeline.git.branch >> ]
          - matches:
              pattern: /^release\/\d+\.\d+\.\d+$/
              value: << pipeline.git.branch >>
      steps:
        - run:
            name: Set environment variable to determine whether or not to persist artifacts
            command: |
              echo "Setting SHOULD_PERSIST_ARTIFACTS variable"
              echo 'export SHOULD_PERSIST_ARTIFACTS=true\n' >> "$BASH_ENV"
