#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
if git diff --cached --name-only | grep -q "^\.circleci/src/"; then
  yarn pack-ci
else
  echo "⏭️ No CircleCI configurations changed, skipping CI packaging"
fi

npx lint-staged
