#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Pack CircleCI config if any files in pull-request were changed
if git diff --cached --name-only | grep -q "^\.circleci/pull-request/"; then
  echo "Packing CircleCI configuration..."
  circleci config pack ./.circleci/pull-request > ./.circleci/pull-request.yml
  git add ./.circleci/pull-request.yml
fi

npx lint-staged
